### ISSUE TITLE
[feature] set brightness of LEDs

### ISSUE THREAD

**Issue by tobiasehlert** [gaussmeter/lumen#1]
I have a suggestion for the lumen tool and that is to provide some possibility to set the brightness of the LED strip.

Personally I run mine in our guestroom and during the day, it's totally fine with the brightness it has. But at late evening and night, the LEDs do illuminate the whole room, so it would be nice to dim it down a little.

First suggestion would be the adjustment of brightness in overall with a value being able to pass into the lumen container.

Second suggestion would be to have some schedule saying like:
_daytime (6-18) 100%
nighttime 20%_

Lets me know if that is something you think would be handy or not :)

Regards,
Tobias

**Comment by LelandSindt** [comment]
My preference would be to add an endpoint... perhaps `/lumen/bright` that sets a global maximum brightness that is applied in [pixelWrapper](https://github.com/gaussmeter/lumen/blob/master/lumen.py#L224)...

You could then create a couple of cron jobs to set the brightness at the appropriate times.   

It might not play well with the pulse animation.... (the pulse animation adjusts brightness over time) 

How does that sound?

**Comment by tobiasehlert** [comment]
Endpoint sounds good for one point, but as you say, the pulse or other animations don't apply for that then. Maybe we could do a use of the brightness setting there as well? Like lowering the total pulse brightness based on percentage or so?
I'm just thinking out loud right now :-D

**Comment by LelandSindt** [comment]
What I meant to convey is.... the pulse animation adjusts brightness over time, it might not translate well with a lower maximum brightness.

Have a look at https://github.com/gaussmeter/lumen/compare/max_bright  ---- it's a bit of a hack but it should work...

I pushed the image to `gaussmeter/lumen:max_bright`

**Comment by LelandSindt** [comment]
`curl -i -X PUT -d '{"max_bright":255}' localhost:9000/lumen/max_bright`

**Comment by LelandSindt** [comment]
You will need to start the lumen command with the `--publish` option.... 

`docker container run --detach --restart always --publish 127.0.0.1:9000:9000 --network gaussmeter --name lumen --privileged  gaussmeter/lumen:max_bright`

**Comment by LelandSindt** [comment]
Have you had a chance to review the changes? 

I am thinking about changing the endpoint to `/settings` before merging to master... 

let me know if you have any questions or concerns.

**Comment by tobiasehlert** [comment]
Hi @LelandSindt,

Sorry for the late reply, totally forgot to reply to you!

I think it's perfect this way.. I've created a cronjob that performs the request atm, but I'll probably integrate it into my Homey to get it dimmed based on sunset/sunrise.

Regarding brightness on animations, what do you think about implementing some calculation of the brightness?
My suggestion is like this, that _Teslamater_ does only send 0-100% in terms of brightness and that _Lumen_ translates the e.g. 75% to 191 (100% to be 255) instead, so you can let the animation part be the same but that _Lumen_ does a little calculation.
On this way, _Teslamater_ does only need to focus on sending the brightness percentage but _Lumen_ adjusts it to the actual value used to set on the LED strip.

And using `/settings` is totally fine as well.. in case you want to add more stuff later on :)

Regards,
Tobias

**Comment by LelandSindt** [comment]
No worries, 

I pushed a commit that scales the brightness input from 0-100 to 0-255. --- let me know if that is what you are looking for. 

I am a _little_ hesitant to push these changes to master because I am lazy and don't want to re-write the defaults that teslamater pushes.. :smile:

**Comment by tobiasehlert** [comment]
Hi @LelandSindt,
Do you want to merge the code from branch [max_bright](https://github.com/gaussmeter/lumen/tree/max_bright) to master? 😄

**Comment by LelandSindt** [comment]
This is embarrassing... I can't even get the master branch to build a container image.. Likely because the dependencies references are not version specific..... 

I also have plans to move away from dockerhub to ghcr and github actions... 

I need to take some time to knock the rust off this project (and its companion services) and come up to speed on github actions.

Thanks for the nudge...

**Comment by LelandSindt** [comment]
resolved by #2
